Addign information collection after CI failure
Signed-off-by: Serguei Bezverkhi <sbezverk@cisco.com>

diff --git a/scripts/integration-tests b/scripts/integration-tests
--- a/scripts/integration-tests
+++ b/scripts/integration-tests
@@ -28,6 +28,21 @@ KUBECTL_VERSION=v1.10.3
 curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl && \
 	chmod +x kubectl && sudo mv kubectl /usr/local/bin/
 
+#
+# In case if a failure, collecting some evidence for further debugging
+#
+function error_collection {
+kubectl get pods --all-namespaces
+nsm=$(kubectl get pods --all-namespaces | grep networkservice | awk '{print $2}')
+namespace=$(kubectl get pods --all-namespaces | grep networkservice | awk '{print $1}')
+if [[ "x$nsm" != "x" ]]; then 
+   kubectl describe pod $nsm -n $namespace
+   kubectl logs $nsm -n $namespace
+   kubectl logs $nsm -n $namespace -p
+fi
+exit 1
+}
+
 # __main__ () {
 . scripts/cluster_common.bash
 
@@ -51,7 +66,7 @@ kubectl create -f conf/sample/networkservice-daemonset.yaml
 echo "INFO: Waiting for Network Service Mesh daemonset to be up and CRDs to be available ..."
 typeset -i cnt=120
 until kubectl get crd | grep networkservicemesh.io ; do
-    ((cnt=cnt-1)) || exit 1
+    ((cnt=cnt-1)) || error_collection
     sleep 2
 done
 
